
  CREATE TABLE "SCOTT"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DEP_NAME" VARCHAR2(14 BYTE), 
	"NUMBER_OF_EMP" VARCHAR2(13 BYTE), 
	"MGR_SSN" NUMBER, 
	 CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "DEPT_EMPLOYEE_FK1" FOREIGN KEY ("MGR_SSN")
	  REFERENCES "SCOTT"."EMPLOYEE" ("SSN") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "SCOTT"."EMPLOYEE" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"JOP_TITTLE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"DEP_ID" NUMBER, 
	"BIRTH_DATE" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER, 
	"SSN" NUMBER NOT NULL ENABLE, 
	"GENDER" VARCHAR2(20 BYTE), 
	"SUPER_SSN" NUMBER, 
	 CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("SSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "EMPLOYEE_DEPT_FK1" FOREIGN KEY ("DEP_ID")
	  REFERENCES "SCOTT"."DEPT" ("DEPTNO") ENABLE, 
	 CONSTRAINT "EMPLOYEE_EMPLOYEE_FK1" FOREIGN KEY ("SUPER_SSN")
	  REFERENCES "SCOTT"."EMPLOYEE" ("SSN") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "SCOTT"."MEAL" 
   (	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20 BYTE), 
	"COST" VARCHAR2(20 BYTE), 
	"SIZE" VARCHAR2(20 BYTE), 
	"CALORIES" VARCHAR2(20 BYTE), 
	"ORD_NUM" NUMBER, 
	 CONSTRAINT "MEAL_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEAL_ORDERS_FK1" FOREIGN KEY ("ORD_NUM")
	  REFERENCES "SCOTT"."ORDERS" ("ORDER_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "SCOTT"."ORDERS" 
   (	"ORDER_NUM" NUMBER NOT NULL ENABLE, 
	"COST" NUMBER NOT NULL ENABLE, 
	"TIME" NUMBER, 
	"EMP_SNN" NUMBER, 
	"DATE" VARCHAR2(20 BYTE), 
	"TYPES" VARCHAR2(20 BYTE), 
	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ORDERS_EMPLOYEE_FK1" FOREIGN KEY ("EMP_SNN")
	  REFERENCES "SCOTT"."EMPLOYEE" ("SSN") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
